### ISSUE TITLE
Create a menu

### ISSUE THREAD

**Issue by agentry5** [agentry5/python-exercise-gentry#1]
**PBI (User story)**:
As a user, I need to be able to interact with this list of movies through some kind of menu, since I do not understand computer language. No program exists yet to serve this purpose.
 * Persona: User with access to these python programs and movies.txt file
 * Feature: User has access to input menu for query.py
 * Business value: Users will be able to interact with the list of movies in movies.txt

**Description**:
Users should have access to a menu when running query.py. This menu is controlled by user-input via the keyboard. 
The menu should have the following options, but only the first two should serve any function:
1. If the user types "q" the program will quit/exit.
2. If the user types any invalid command, the menu will simply reappear and allow them to input again.
3. If the user types "sn" they can search the list of movies by their name.
4. If the user types "sc" they can search the list the list of movies by their cast.
5. If the user types "list" they can print the name of every movie in the list.

**Task List**:
- [x] Program should list all available options above
- [x] Read keyboard input from user 
- [x] "q" input functionality
- [x] Invalid input functionality

**Acceptance Criteria**:
1. Program runs indefinitely
2. All above options print properly spaced

**Acceptance Tests**:
1. Typing q exits the program (Program does not end otherwise)
2. Any other input repeats menu
